# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Alteruser.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Alteruser(object):
    def setupUi(self, Dialog_Alteruser):
        Dialog_Alteruser.setObjectName("Dialog_Alteruser")
        Dialog_Alteruser.resize(478, 358)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_Alteruser.sizePolicy().hasHeightForWidth())
        Dialog_Alteruser.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog_Alteruser)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_userID = QtWidgets.QLabel(Dialog_Alteruser)
        self.label_userID.setMinimumSize(QtCore.QSize(60, 30))
        self.label_userID.setObjectName("label_userID")
        self.horizontalLayout.addWidget(self.label_userID)
        self.comboBox_userID = QtWidgets.QComboBox(Dialog_Alteruser)
        self.comboBox_userID.setMinimumSize(QtCore.QSize(100, 30))
        self.comboBox_userID.setObjectName("comboBox_userID")
        self.comboBox_userID.addItem("")
        self.comboBox_userID.addItem("")
        self.comboBox_userID.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_userID)
        self.label_username = QtWidgets.QLabel(Dialog_Alteruser)
        self.label_username.setMinimumSize(QtCore.QSize(50, 30))
        self.label_username.setObjectName("label_username")
        self.horizontalLayout.addWidget(self.label_username)
        self.lineEdit_username = QtWidgets.QLineEdit(Dialog_Alteruser)
        self.lineEdit_username.setMinimumSize(QtCore.QSize(80, 30))
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.horizontalLayout.addWidget(self.lineEdit_username)
        self.pushButton_query = QtWidgets.QPushButton(Dialog_Alteruser)
        self.pushButton_query.setEnabled(False)
        self.pushButton_query.setMinimumSize(QtCore.QSize(60, 30))
        self.pushButton_query.setObjectName("pushButton_query")
        self.horizontalLayout.addWidget(self.pushButton_query)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_viewall = QtWidgets.QPushButton(Dialog_Alteruser)
        self.pushButton_viewall.setMinimumSize(QtCore.QSize(60, 30))
        self.pushButton_viewall.setObjectName("pushButton_viewall")
        self.gridLayout.addWidget(self.pushButton_viewall, 0, 0, 1, 1)
        self.label_newname = QtWidgets.QLabel(Dialog_Alteruser)
        self.label_newname.setMinimumSize(QtCore.QSize(0, 30))
        self.label_newname.setAlignment(QtCore.Qt.AlignCenter)
        self.label_newname.setObjectName("label_newname")
        self.gridLayout.addWidget(self.label_newname, 1, 0, 1, 1)
        self.label_newpwd = QtWidgets.QLabel(Dialog_Alteruser)
        self.label_newpwd.setMinimumSize(QtCore.QSize(0, 30))
        self.label_newpwd.setAlignment(QtCore.Qt.AlignCenter)
        self.label_newpwd.setObjectName("label_newpwd")
        self.gridLayout.addWidget(self.label_newpwd, 1, 1, 1, 1)
        self.label_newID = QtWidgets.QLabel(Dialog_Alteruser)
        self.label_newID.setMinimumSize(QtCore.QSize(0, 30))
        self.label_newID.setAlignment(QtCore.Qt.AlignCenter)
        self.label_newID.setObjectName("label_newID")
        self.gridLayout.addWidget(self.label_newID, 1, 2, 1, 1)
        self.lineEdit_newname = QtWidgets.QLineEdit(Dialog_Alteruser)
        self.lineEdit_newname.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_newname.setObjectName("lineEdit_newname")
        self.gridLayout.addWidget(self.lineEdit_newname, 2, 0, 1, 1)
        self.lineEdit_newpwd = QtWidgets.QLineEdit(Dialog_Alteruser)
        self.lineEdit_newpwd.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_newpwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_newpwd.setObjectName("lineEdit_newpwd")
        self.gridLayout.addWidget(self.lineEdit_newpwd, 2, 1, 1, 1)
        self.comboBox_newID = QtWidgets.QComboBox(Dialog_Alteruser)
        self.comboBox_newID.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_newID.setObjectName("comboBox_newID")
        self.comboBox_newID.addItem("")
        self.comboBox_newID.addItem("")
        self.comboBox_newID.addItem("")
        self.gridLayout.addWidget(self.comboBox_newID, 2, 2, 1, 1)
        self.pushButton_alter = QtWidgets.QPushButton(Dialog_Alteruser)
        self.pushButton_alter.setEnabled(False)
        self.pushButton_alter.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_alter.setObjectName("pushButton_alter")
        self.gridLayout.addWidget(self.pushButton_alter, 2, 3, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setColumnStretch(2, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.tableWidget_userInfo = QtWidgets.QTableWidget(Dialog_Alteruser)
        self.tableWidget_userInfo.setMinimumSize(QtCore.QSize(0, 30))
        self.tableWidget_userInfo.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_userInfo.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_userInfo.setRowCount(10)
        self.tableWidget_userInfo.setColumnCount(4)
        self.tableWidget_userInfo.setObjectName("tableWidget_userInfo")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_userInfo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_userInfo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_userInfo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_userInfo.setHorizontalHeaderItem(3, item)
        self.tableWidget_userInfo.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_userInfo.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.tableWidget_userInfo, 1, 0, 1, 1)

        self.retranslateUi(Dialog_Alteruser)
        self.comboBox_userID.setCurrentIndex(-1)
        self.comboBox_newID.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Alteruser)

    def retranslateUi(self, Dialog_Alteruser):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Alteruser.setWindowTitle(_translate("Dialog_Alteruser", "修改用户信息"))
        self.label_userID.setText(_translate("Dialog_Alteruser", "用户身份"))
        self.comboBox_userID.setItemText(0, _translate("Dialog_Alteruser", "安全工程师"))
        self.comboBox_userID.setItemText(1, _translate("Dialog_Alteruser", "操纵员"))
        self.comboBox_userID.setItemText(2, _translate("Dialog_Alteruser", "一般用户"))
        self.label_username.setText(_translate("Dialog_Alteruser", "用 户 名"))
        self.pushButton_query.setText(_translate("Dialog_Alteruser", "查询"))
        self.pushButton_viewall.setText(_translate("Dialog_Alteruser", "显示所有用户"))
        self.label_newname.setText(_translate("Dialog_Alteruser", "新 用 户 名"))
        self.label_newpwd.setText(_translate("Dialog_Alteruser", "新 密 码"))
        self.label_newID.setText(_translate("Dialog_Alteruser", "新 用 户 身 份"))
        self.comboBox_newID.setItemText(0, _translate("Dialog_Alteruser", "安全工程师"))
        self.comboBox_newID.setItemText(1, _translate("Dialog_Alteruser", "操纵员"))
        self.comboBox_newID.setItemText(2, _translate("Dialog_Alteruser", "一般用户"))
        self.pushButton_alter.setText(_translate("Dialog_Alteruser", "更 改"))
        item = self.tableWidget_userInfo.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_Alteruser", "用户名"))
        item = self.tableWidget_userInfo.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_Alteruser", "密码"))
        item = self.tableWidget_userInfo.horizontalHeaderItem(2)
        item.setText(_translate("Dialog_Alteruser", "用户身份"))
        item = self.tableWidget_userInfo.horizontalHeaderItem(3)
        item.setText(_translate("Dialog_Alteruser", "用户权限"))
