# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Deleteuser.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_DeleteUser(object):
    def setupUi(self, Dialog_DeleteUser):
        Dialog_DeleteUser.setObjectName("Dialog_DeleteUser")
        Dialog_DeleteUser.resize(488, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_DeleteUser.sizePolicy().hasHeightForWidth())
        Dialog_DeleteUser.setSizePolicy(sizePolicy)
        Dialog_DeleteUser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout = QtWidgets.QGridLayout(Dialog_DeleteUser)
        self.gridLayout.setHorizontalSpacing(160)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_userID = QtWidgets.QLabel(Dialog_DeleteUser)
        self.label_userID.setMinimumSize(QtCore.QSize(60, 30))
        self.label_userID.setObjectName("label_userID")
        self.horizontalLayout.addWidget(self.label_userID)
        self.comboBox_userID = QtWidgets.QComboBox(Dialog_DeleteUser)
        self.comboBox_userID.setMinimumSize(QtCore.QSize(100, 30))
        self.comboBox_userID.setObjectName("comboBox_userID")
        self.comboBox_userID.addItem("")
        self.comboBox_userID.addItem("")
        self.comboBox_userID.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_userID)
        self.label_username = QtWidgets.QLabel(Dialog_DeleteUser)
        self.label_username.setMinimumSize(QtCore.QSize(60, 30))
        self.label_username.setObjectName("label_username")
        self.horizontalLayout.addWidget(self.label_username)
        self.lineEdit_username = QtWidgets.QLineEdit(Dialog_DeleteUser)
        self.lineEdit_username.setMinimumSize(QtCore.QSize(80, 30))
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.horizontalLayout.addWidget(self.lineEdit_username)
        self.pushButton_query = QtWidgets.QPushButton(Dialog_DeleteUser)
        self.pushButton_query.setEnabled(False)
        self.pushButton_query.setMinimumSize(QtCore.QSize(60, 30))
        self.pushButton_query.setObjectName("pushButton_query")
        self.horizontalLayout.addWidget(self.pushButton_query)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.pushButton_viewall = QtWidgets.QPushButton(Dialog_DeleteUser)
        self.pushButton_viewall.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_viewall.setObjectName("pushButton_viewall")
        self.gridLayout.addWidget(self.pushButton_viewall, 2, 0, 1, 1)
        self.pushButton_delete = QtWidgets.QPushButton(Dialog_DeleteUser)
        self.pushButton_delete.setEnabled(False)
        self.pushButton_delete.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.gridLayout.addWidget(self.pushButton_delete, 2, 1, 1, 1)
        self.tableWidget_userInfo = QtWidgets.QTableWidget(Dialog_DeleteUser)
        self.tableWidget_userInfo.setMinimumSize(QtCore.QSize(0, 30))
        self.tableWidget_userInfo.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_userInfo.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_userInfo.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_userInfo.setRowCount(10)
        self.tableWidget_userInfo.setObjectName("tableWidget_userInfo")
        self.tableWidget_userInfo.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_userInfo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_userInfo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_userInfo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_userInfo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_userInfo.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_userInfo.setItem(0, 3, item)
        self.tableWidget_userInfo.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_userInfo.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget_userInfo.horizontalHeader().setHighlightSections(True)
        self.tableWidget_userInfo.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_userInfo.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableWidget_userInfo, 1, 0, 1, 2)

        self.retranslateUi(Dialog_DeleteUser)
        self.comboBox_userID.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Dialog_DeleteUser)

    def retranslateUi(self, Dialog_DeleteUser):
        _translate = QtCore.QCoreApplication.translate
        Dialog_DeleteUser.setWindowTitle(_translate("Dialog_DeleteUser", "删除用户"))
        self.label_userID.setText(_translate("Dialog_DeleteUser", "用户身份"))
        self.comboBox_userID.setItemText(0, _translate("Dialog_DeleteUser", "安全工程师"))
        self.comboBox_userID.setItemText(1, _translate("Dialog_DeleteUser", "操纵员"))
        self.comboBox_userID.setItemText(2, _translate("Dialog_DeleteUser", "一般用户"))
        self.label_username.setText(_translate("Dialog_DeleteUser", "用 户 名"))
        self.pushButton_query.setText(_translate("Dialog_DeleteUser", "查询"))
        self.pushButton_viewall.setText(_translate("Dialog_DeleteUser", "显示所有用户"))
        self.pushButton_delete.setText(_translate("Dialog_DeleteUser", "删除"))
        item = self.tableWidget_userInfo.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_DeleteUser", "用户名"))
        item = self.tableWidget_userInfo.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_DeleteUser", "密码"))
        item = self.tableWidget_userInfo.horizontalHeaderItem(2)
        item.setText(_translate("Dialog_DeleteUser", "用户身份"))
        item = self.tableWidget_userInfo.horizontalHeaderItem(3)
        item.setText(_translate("Dialog_DeleteUser", "用户权限"))
        __sortingEnabled = self.tableWidget_userInfo.isSortingEnabled()
        self.tableWidget_userInfo.setSortingEnabled(False)
        self.tableWidget_userInfo.setSortingEnabled(__sortingEnabled)
