# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login_read_txt.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(699, 571)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout.setObjectName("gridLayout")
        self.label_identity = QtWidgets.QLabel(self.widget_5)
        self.label_identity.setMinimumSize(QtCore.QSize(0, 40))
        self.label_identity.setObjectName("label_identity")
        self.gridLayout.addWidget(self.label_identity, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.widget_5)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 40))
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        self.label_username = QtWidgets.QLabel(self.widget_5)
        self.label_username.setMinimumSize(QtCore.QSize(0, 40))
        self.label_username.setObjectName("label_username")
        self.gridLayout.addWidget(self.label_username, 1, 0, 1, 1)
        self.lineEdit_username = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_username.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.gridLayout.addWidget(self.lineEdit_username, 1, 1, 1, 1)
        self.label_pwd = QtWidgets.QLabel(self.widget_5)
        self.label_pwd.setMinimumSize(QtCore.QSize(0, 40))
        self.label_pwd.setObjectName("label_pwd")
        self.gridLayout.addWidget(self.label_pwd, 2, 0, 1, 1)
        self.lineEdit_pwd = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_pwd.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_pwd.setObjectName("lineEdit_pwd")
        self.gridLayout.addWidget(self.lineEdit_pwd, 2, 1, 1, 1)
        self.pushButton_read_user_txt = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_read_user_txt.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_read_user_txt.setObjectName("pushButton_read_user_txt")
        self.gridLayout.addWidget(self.pushButton_read_user_txt, 3, 0, 1, 2)
        self.pushButton_login = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_login.setEnabled(False)
        self.pushButton_login.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_login.setObjectName("pushButton_login")
        self.gridLayout.addWidget(self.pushButton_login, 4, 0, 1, 2)
        self.pushButton_regist = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_regist.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_regist.setObjectName("pushButton_regist")
        self.gridLayout.addWidget(self.pushButton_regist, 5, 0, 1, 2)
        self.verticalLayout.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.widget_2)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout.addWidget(self.widget_6)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 1)
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout.addWidget(self.widget_3)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "智能运行支持系统"))
        self.label_identity.setText(_translate("Form", "选择身份"))
        self.comboBox.setItemText(0, _translate("Form", "管理员"))
        self.comboBox.setItemText(1, _translate("Form", "操纵员"))
        self.comboBox.setItemText(2, _translate("Form", "安全工程师"))
        self.comboBox.setItemText(3, _translate("Form", "一般用户"))
        self.label_username.setText(_translate("Form", "用户名"))
        self.label_pwd.setText(_translate("Form", "密 码"))
        self.pushButton_read_user_txt.setText(_translate("Form", "读取用户数据"))
        self.pushButton_login.setText(_translate("Form", "验证登录"))
        self.pushButton_regist.setText(_translate("Form", "用户注册"))
